services:
  - type: web
    name: quantumtrade-virtual-stock-trading
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
